<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
<HEAD>
<?php
if (isset($javascript) && $javascript)
	echo "<SCRIPT LANGUAGE=\"javascript\">".$javascript."</SCRIPT>\n";
?>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=utf-8">
<TITLE>YALA</TITLE>
<STYLE TYPE="text/css">
	TABLE { border-style: none; margin: 3; }
	TABLE.dense { border-style: none; border-spacing: 0; margin: 0; padding: 0; }
	TABLE.toolbar	{ border: thin dotted black; background-color: #E5EFFF; }
	TABLE.error { border: thin dotted black; margin-top: 8%; }
	A:link,A:visited { color: #3333CC; text-decoration: none; }
	A:hover { background-color: #D5DFFF; text-decoration: underline; }
	TR.dnbgcolor { background-color: #B5BFEF; }
	TR.bgcolor1  { background-color: #C5CFEF; }
	TR.bgcolor2  { background-color: #E5EFFF; }
	TD.dnattr { color: #000066; font-weight: bold; font-size: large; }
	TD.attr	  { color: #222266; width: 35%; }
	TD.value  { color: #222266; }
	TD.dense	{ padding: 0; border-spacing: 0; }
	HR { border: 1px dashed #B5BFEF; }
	ACRONYM { border-bottom: 1px dotted #333; cursor: help; }
	BODY {
		background-color:ghostwhite;
	}
</STYLE>
</HEAD>
<BODY>
