#! /bin/sh

set -e
(
dpkg-divert --package se3 --add --rename --divert /etc/.cron_mrtg.divert /etc/cron.d/mrtg
dpkg-divert --package se3 --add --rename --divert /etc/mrtg.cfg.divert /etc/mrtg.cfg 
dpkg-divert --package se3 --add --rename --divert /usr/share/backuppc/image/BackupPC_stnd.css.divert /usr/share/backuppc/image/BackupPC_stnd.css 
dpkg-divert --package se3 --add --rename --divert /etc/backuppc/apache.conf.divert /etc/backuppc/apache.conf 
dpkg-divert --package se3 --add --rename --divert /usr/share/backuppc/lib/BackupPC/CGI/Lib.pm.divert /usr/share/backuppc/lib/BackupPC/CGI/Lib.pm 
dpkg-divert --package se3 --add --rename --divert  /etc/php5/apache2/php.ini.divert /etc/php5/apache2/php.ini 
dpkg-divert --package se3 --add --rename --divert /etc/php5/cli/php.ini.divert /etc/php5/cli/php.ini 
dpkg-divert --package se3 --add --rename --divert /etc/default/apache2.divert  /etc/default/apache2 

dpkg-divert --package se3 --add --rename --divert /etc/cups/mime.convs.divert  /etc/cups/mime.convs 
dpkg-divert --package se3 --add --rename --divert /etc/cups/mime.types.divert  /etc/cups/mime.types 
dpkg-divert --package se3 --add --rename --divert /etc/syslog.conf.divert /etc/syslog.conf 

dpkg-divert --package se3 --add --rename --divert /usr/share/se3/scripts/start_poste.divert /usr/share/se3/scripts/start_poste.sh

# No rename, may have real conf in place (reinstall for exemple)
dpkg-divert --package se3 --add --divert /etc/samba/smb.conf.divert  /etc/samba/smb.conf 
dpkg-divert --package se3 --add --divert  /etc/ssmtp/ssmtp.conf.divert  /etc/ssmtp/ssmtp.conf 
dpkg-divert --package se3 --add --divert /etc/backuppc/config.pl.divert /etc/backuppc/config.pl 
dpkg-divert --package se3 --add --divert /etc/backuppc/localhost.pl.divert  /etc/backuppc/localhost.pl
dpkg-divert --package se3 --add --divert  /etc/ldap/slapd.conf.divert /etc/ldap/slapd.conf
dpkg-divert --package se3 --add --divert  /etc/ldap/ldap.conf.divert /etc/ldap/ldap.conf 
dpkg-divert --package se3 --add --divert  /etc/nsswitch.conf.divert /etc/nsswitch.conf 
dpkg-divert --package se3 --add --divert  /etc/pam_ldap.conf.divert /etc/pam_ldap.conf 
dpkg-divert --package se3 --add --divert  /etc/libnss-ldap.conf.divert /etc/libnss-ldap.conf 
) >/dev/null

# Nettoyage se3_install
if [ -d /var/cache/se3_install/reg ]; then
rm -rf /var/cache/se3_install/reg
fi

if [ -d /var/cache/se3_install/unattended ]; then
rm -rf /var/cache/se3_install/unattended
fi

# Nettoyage etc

if [ -e /etc/logrotate.d/se3-logrotate ]; then
rm -f /etc/logrotate.d/se3-logrotate
fi

# Nettoyage sbin

if [ -e /usr/share/se3/sbin/LcsCanSee.pl ]; then
rm -f /usr/share/se3/sbin/LcsCanSee.pl
fi

if [ -e /usr/share/se3/sbin/connexion.pl ]; then
rm -f /usr/share/se3/sbin/connexion.pl
fi

if [ -e /usr/share/se3/sbin/connexion.sh ]; then
rm -f /usr/share/se3/sbin/connexion.sh
fi

if [ -e /usr/share/se3/sbin/cryptcons ]; then
rm -f /usr/share/se3/sbin/cryptcons
fi

if [ -e /usr/share/se3/sbin/deconnexion.pl ]; then
rm -f /usr/share/se3/sbin/deconnexion.pl
fi

if [ -e /usr/share/se3/sbin/del_profilsXP.sh ]; then
rm -f /usr/share/se3/sbin/del_profilsXP.sh
fi

if [ -e /usr/share/se3/sbin/lanceur_applications.sh ]; then
rm -f /usr/share/se3/sbin/lanceur_applications.sh
fi

if [ -e /usr/share/se3/sbin/maj58bis.sh ]; then
rm -f /usr/share/se3/sbin/maj58bis.sh
fi

if [ -e /usr/share/se3/sbin/migration_ldap_etch.sh ]; then
rm -f /usr/share/se3/sbin/migration_ldap_etch.sh
fi

if [ -e /usr/share/se3/sbin/mkhome.pl ]; then
rm -f /usr/share/se3/sbin/mkhome.pl
fi

if [ -e /usr/share/se3/sbin/parti.pl ]; then
rm -f /usr/share/se3/sbin/parti.pl
fi

if [ -e /usr/share/se3/sbin/se3_proxy.sh ]; then
rm -f /usr/share/se3/sbin/se3_proxy.sh
fi

if [ -e /usr/share/se3/sbin/se3_upgrade_etch.sh ]; then
rm -f /usr/share/se3/sbin/se3_upgrade_etch.sh
fi

if [ -e /usr/share/se3/sbin/smb_rootexec.sh ]; then
rm -f /usr/share/se3/sbin/smb_rootexec.sh
fi

if [ -e /usr/share/se3/sbin/updatese3.sh ]; then
rm -f /usr/share/se3/sbin/updatese3.sh
fi


if [ -e /usr/share/se3/sbin/se3_reinit_mdp.sh ]; then
rm -f /usr/share/se3/sbin/se3_reinit_mdp.sh
fi


if [ -e /usr/share/se3/sbin/gon2posix.sh ]; then
rm -f /usr/share/se3/sbin/gon2posix.sh
fi


if [ -e /usr/share/se3/sbin/permse3 ]; then
rm -f /usr/share/se3/sbin/permse3
ln -s /usr/share/se3/scripts/permse3 /usr/share/se3/sbin/permse3 
fi

#if [ -e  ]; then
#rm -f 
#fi

# Nettoyage scripts

if [ -e /usr/share/se3/scripts/change_root_smbpass.sh ]; then
rm -f /usr/share/se3/scripts/change_root_smbpass.sh
fi

if [ -e /usr/share/se3/scripts/cryptcons ]; then
rm -f /usr/share/se3/scripts/cryptcons
fi

if [ -e /usr/share/se3/scripts/maj_zi.sh ]; then
rm -f /usr/share/se3/scripts/maj_zi.sh
fi

if [ -e /usr/share/se3/scripts/unattent_appli.sh ]; then
rm -f /usr/share/se3/scripts/unattent_appli.sh
fi

if [ -e /usr/share/se3/scripts/verif_client.sh ]; then
rm -f /usr/share/se3/scripts/verif_client.sh
fi

if [ -e /usr/share/se3/scripts/delEntryClientIni.sh ]; then
rm -f /usr/share/se3/scripts/delEntryClientIni.sh
fi

exit 0
