<?
// $Id$ //

$name_obj="Maintenance";  // Nom qui apparait dans l'interface
$basesql_obj="inventaire";   // Nom dans la base SQL qui permet de désactiver cet objeta
$name_id="maintenance";

// Ajout d'une nouvelle machine
$objet['add'] = array('computer.png','Signaler une machine en maintenance','popuprecherche(\'../ocsreports/maintenance.php\',\'popuprecherche\',\'scrollbars=yes,width=500,height=500\')','maintenance_add');
?>
