#!/bin/bash
# convertit les quotas xfs au format attendu par samba4.1
user=$3
mnt=$(stat -c %m -- $(pwd))
RET=$(xfs_quota -x -c "quota -bi -N -u $user"  $mnt 2>/dev/null) && \
if [ -n "$RET" ]; then
    echo $RET |  awk '{ gsub (/\[(([0-9]*) days)\]/,""); gsub (/\[-*\]/,""); print "2 "$2" "$3" "$4" "$6" "$7" "$8" 1024" }'
    exit 0
fi
echo "2 0 0 0 0 0 0 1024"
exit 0
